# Generated by Django 3.2.18 on 2023-08-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
